carts/urls.py
from django.urls import path

from carts.views import cart_add, cart_remove, cart_edit

app_name = 'carts'

urlpatterns = [
    path('add/<int:product_id>', cart_add, name='cart_add'),
    path('remove/<int:id>', cart_remove, name='cart_remove'),
    path('edit/<int:id>/<int:quantity>/', cart_edit, name='cart_edit'),

]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from products.views import index, products

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('carts/', include('carts.urls', namespace='carts')),
    path('admin-staff/', include('admins.urls', namespace='admins')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/models.py
from django.db import models
from users.models import User
from products.models import Product


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username} | {self.product.name}'

    def amount(self):
        return self.quantity * self.product.price

    def total_quantity(self):
        carts = Cart.objects.filter(user=self.user)
        return sum(cart.quantity for cart in carts)

    def total_sum(self):
        carts = Cart.objects.filter(user=self.user)
        return sum(cart.amount() for cart in carts)

carts/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string
from django.http import JsonResponse
from products.models import Product
from carts.models import Cart


@login_required
def cart_add(request, product_id):
    product = Product.objects.get(id=product_id)
    carts = Cart.objects.filter(user=request.user, product=product)

    if not carts.exists():
        Cart.objects.create(user=request.user, product=product, quantity=1)
    else:
        cart = carts.first()
        cart.quantity += 1
        cart.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def cart_remove(request, id):
    cart = Cart.objects.get(id=id)
    cart.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def cart_edit(request, id, quantity):
    if request.is_ajax():
        cart = Cart.objects.get(id=id)
        if quantity > 0:
            cart.quantity = quantity
            cart.save()
        else:
            cart.delete()
        carts = Cart.objects.filter(user=request.user)
        context = {'carts': carts}
        result = render_to_string('carts/cart.html', context)
        return JsonResponse({'result': result})

carts/templates/carts/cart.html
<div class="cart_list">
    {% if carts %}
        <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
            Cart <span class="badge badge-secondary badge-pill">{{ carts.0.total_quantity }}</span>
        </h4>
        {% for cart in carts %}
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">{{ cart.product.name }}</h5>
                    <p class="card-text">{{ cart.product.description }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item bg-light">
                        <div class="row text-center">
                            <div class="col-lg-4">
                                <input name="{{ cart.id }}" type="number" class="form-control" value="{{ cart.quantity }}" min="0">
                            </div>
                            <div class="col-lg-4">$ {{ cart.amount }}</div>
                                <div class="col-lg-4">
                                    <a href="{% url 'carts:cart_remove' cart.id %}">
                                        <i class="fas fa-trash"></i>
                                    </a>
                                </div>
                            </div>
                    </li>
                </ul>
            </div>
        {% endfor %}
        <div class="card mb-3">
            <div class="card-footer">
                <p class="float-left">Total</p>
            <h4 class="float-right">$ {{ carts.0.total_sum }}</h4>
            </div>
        </div>
        <button type="button" class="btn btn-success btn-lg float-right">Оформить</button>
    {% else %}
        <h4 class="mt-3 mb-3 mb-3 text-center">
            Cart is empty <span class="badge badge-secondary badge-pill">3</span>
        </h4>
    {% endif %}
</div>